In [0]:
import requests
from IPython.core.display import HTML
HTML(f"""
<style>
</style>
""")

# Experimenting with the tutorial

**Overview**
This exercise is related to the week 4 tutorial.
 
The individual tasks will ask you to either reflect on parts of the tutorial or modify specific code cells from the tutorial. Specifically, [Task 2](#project) and [Task 3](#ls) require modifications to the code of the tutorial notebook.
 


<article class="message">
    <div class="message-body">
        <strong>List of tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#copy">Task 1: Copy notebook</a>
            </li>
            <li>
            <a href="#project">Task 2: Projection experiments</a>
            </li>
            <li>
            <a href="#ls">Task 3: Linear Least Squares Experiments</a>
            </li>
            <li>
            <a href="#ls1">Task 4: Linear Least Squares Reflections</a>
            </li>
            <li>
            <a href="#poly">Task 5: Second-order polynomial</a>
            </li>
            <li>
            <a href="#pmatrix">Task 6: Projection matrix</a>
            </li>
        </ul>
    </div>
</article>


---
**Task 1 (easy): Copy notebook**
Copy the tutorial notebook
 in the repository. 
This makes it easy to go back to the original in case something goes wrong.

---
---
**Task 2 (easy): Projection experiments👩‍💻📽️**
This task builds on the $\textbf{Projections}$ section in the tutorial.
1. Search and identify comment `##1`
. 
2. Change the values of the matrix $A$ (below comment `##1`
) to modify the line. Experiment with different values and observe how the projection changes in the plot.
3. Change the matrix $A$, such that $PX$ ≈ $X$ (that is the projection leaves $X$ almost unchanged). 
4. Search and identify comment `##2`
.
5. Set the matrix $A$  = $\begin{bmatrix} 1 \\ 0.5 \end{bmatrix}$, then apply the projection matrix $P$ twice, i.e. calculate $PPX$ (just below the comment). How does this affect the projected points?


---

# task 2 (me trying to understand anything?)
1. the Matrix A is a vector. It has the length 1 and 0.5. Itis the one that we project with P after. 
2. When doing this we can see that the values change a little. Depending on what values you do. If you changed it to [1,0] it is a "vandret" linje, and therefore not very close to the original point. (OBS. Remember this is a vector, and should therefore be seen as to start at the origin (0,0) of the coordinate system.)
3. I guessed around, and found the closest value to be around 0.75, now that this hits the middle point. (This was done by eyeballing the visualisation above the task, and changing the vector according to this.)
4. Found it
5. When doing this, it can be seen that this is the exact same value as PX.
$$
PX = PPX
$$
Which also makes sense. If you give $P$  a list of points $PX$ that are points that already lay on the line, then the closest point to them is on the line itself.


---
**Task 3 (easy): Linear Least Squares Experiments👩‍💻**
This task builds on the $\textbf{Linear Least Squares}$ section in the tutorial.
1. Search and identify comment `##3`
.
2. Change the values of the first point in the matrix `X`
 such that it gradually moves further and further away from the line. Observe how it affects the error $RMS$.
3. Add two points to `X`
 and observe how they affect the fitted line and the error.


---

# Task 3 (me gradually understanding)
1. Found
2. First it can get huge error marks, but i observed that if it gets long enough away, than it was not as bad.
3. I put some wild pictures points in a circle almost, and the error margin was bad, and it was basiccaly in the middle of the circle.



---
**Task 4 (easy): Linear Least Squares Reflections💡📽️**
1. How can you change the two additional points so the fitted line does not move?
2. What happens to the error when removing all but two points from `X`
?
3. What happens when you remove all but one point from `X`
?
4. Reflect on how the quality of the data affects the projection and thus the solution. 


---

# Task 4
1. Add two lines that lay on the same fitted line. This will ensure that it does not change.
2. The RMS becomes zero. The vecctor that is the difference between the original point and the projected point becomes zero for both points.3
3. Then it does not work. Python gives an error. In y = mx + b, there are 2 unknowns, where the x and yx, is taken from the point and inputted. However now that we have 2 unknowns, we need at least 2 points.
4. Chat: "The quality of the data directly impacts the accuracy of the fitted line. If the data is noisy, sparse, or contains outliers, the projection onto the model space becomes less reliable, leading to a poor or biased solution. High-quality, well-distributed data produces a more stable and accurate fit."

## Pen and paper exercises
A 2. order polynomial is given by 

$$f(x) = w_0 + w_1x + w_2x^2 = \sum^2_{i=0} w_ix^i.$$

Generally, an $N$'th order  polynomial is given by

$$f(x) = \sum^N_{i=0} w_ix^i,$$
where $\mathbb{w}$ is a vector of coefficients.

---
**Task 5 (medium): Second-order polynomial♾️📽️**
1. Identify the knowns and unknowns in the polynomial above.
2. Is the function linear or non-linear in $\mathbb{w}$?
3. Is the function linear or non-linear in $\mathbb{x}$?
4. Provide the outline of an algorithm for fitting a second-order polynomial using linear least squares.
5. Generalize this algorithm to n-th order polynomials.


---

# Task 5
1. Knowns: The input variable x and the polynomial order (2).           Unknowns: The coefficients w=[$w_0$,$w_1$,$w_2$].
2. The function is linear in $w$ because each coefficient appears to the first power and is not multiplied by another coefficient. If 2 w's would be timed together at some place, that it is not linear in w. 
3. Non-linear, due to the fact that the arguments are not in the first power, which means the relationship between $x$ and $f(x)$ is curved rather than a straight line.
4. Step 1: Prepare the data
Collect your input data points $(x_i, y_i)$ for $i = 1, \dots, n$.

Step 2: Build the design matrix $X$
For a second-order polynomial, each row is $[1,\ x_i,\ x_i^2]$.
Thus $X \in \mathbb{R}^{n \times 3}$:

$X = \begin{bmatrix}
1 & x_1 & x_1^2 \\
1 & x_2 & x_2^2 \\
\vdots & \vdots & \vdots \\
1 & x_n & x_n^2
\end{bmatrix}$

Step 3: Formulate the normal equations
$\hat{\mathbf{w}} = (X^\top X)^{-1} X^\top \mathbf{y}$.

What is $\mathbf{y}$?
$\mathbf{y}$ is the vector of observed outputs from your dataset, formed by stacking the $y_i$ values:
$\mathbf{y} = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_n \end{bmatrix}$.

You are estimating $\mathbf{w} = [w_0, w_1, w_2]^\top$ so that the predictions $X\mathbf{w}$ are as close as possible to $\mathbf{y}$ in the least-squares sense (i.e., minimizing $|,\mathbf{y} - X\mathbf{w},|_2^2$).

Step 4: Compute $\hat{\mathbf{w}}$
Solve for $\hat{\mathbf{w}} = [\hat{w}_0, \hat{w}_1, \hat{w}_2]^\top$ using the formula above.

Step 5: Predict
Use $\hat{\mathbf{w}}$ to compute predictions:
$\hat{f}(x) = \hat{w}_0 + \hat{w}_1 x + \hat{w}_2 x^2$

5. Step 1: Prepare the data
Collect your input data points $(x_i, y_i)$ for $i = 1, \dots, n$.

Step 2: Build the design matrix $X$
For a n'th-order polynomial, each row is $[1,\ x_i,\ x_i^2,\ ... ,\ x_i^n]$.
Thus $X \in \mathbb{R}^{n \times 3}$:

$X = \begin{bmatrix}
1 & x_1 & x_1^2 & ... & x_1^n \\
1 & x_2 & x_2^2 & ... & x_2^n \\
\vdots & \vdots & \vdots & \vdots & \vdots \\
1 & x_n & x_n^2 & ... & x_n^n
\end{bmatrix}$

Step 3: Formulate the normal equations
$\hat{\mathbf{w}} = (X^\top X)^{-1} X^\top \mathbf{y}$.

What is $\mathbf{y}$?
$\mathbf{y}$ is the vector of observed outputs from your dataset, formed by stacking the $y_i$ values:
$\mathbf{y} = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_n \end{bmatrix}$.

You are estimating $\mathbf{w} = [w_0, w_1, w_2, ..., w_n]^\top$ so that the predictions $X\mathbf{w}$ are as close as possible to $\mathbf{y}$ in the least-squares sense (i.e., minimizing $|,\mathbf{y} - X\mathbf{w},|_2^2$).

Step 4: Compute $\hat{\mathbf{w}}$
Solve for $\hat{\mathbf{w}} = [\hat{w}_0, \hat{w}_1, \hat{w}_2, ..., \hat{w}_n]^\top$ using the formula above.

Step 5: Predict
Use $\hat{\mathbf{w}}$ to compute predictions:
$\hat{f}(x) = \hat{w}_0 + \hat{w}_1 x + \hat{w}_2 x^2 + ... + \hat{w}_n x^n$

In [ ]:
# This section i try to find the inverse of a matrix, because 
# I cannot do it in hand, because im stupid apprently

# This is to genereate the to fit a second order polynomial to 3 points. 

import numpy as np

_X = np.array([
    [1,4,16],
    [1,5,25],
    [1,1,1]
])
y = np.array([7, 6, 2])
_X_tranposed = _X.T

print("X transposed is: \n",_X_tranposed)

# Here i try to find the product of x transposed and x
XT_T = _X_tranposed @ _X
print("X transposed and X is: \n",XT_T)

# the inverse of the above is:
inverse = np.linalg.inv(XT_T)
print("inverse of (X transposed and X) is: \n", inverse)

# (X^T X)^-1 X^T
inverse_with_X_Transposed = inverse @ _X_tranposed
print("(X^T X)^-1 X^T", inverse_with_X_Transposed)

# At last, we now put the y value on:
w_hat = inverse_with_X_Transposed @ y
print("w^hat is: ", w_hat)

# f(x) = -0,66667x^2 + 5x -2,33333

X transposed is: 
 [[ 1  1  1]
 [ 4  5  1]
 [16 25  1]]
X transposed and X is: 
 [[  3  10  42]
 [ 10  42 190]
 [ 42 190 882]]
inverse of (X transposed and X) is: 
 [[ 6.55555556 -5.83333333  0.94444444]
 [-5.83333333  6.125      -1.04166667]
 [ 0.94444444 -1.04166667  0.18055556]]
(X^T X)^-1 X^T [[-1.66666667  1.          1.66666667]
 [ 2.         -1.25       -0.75      ]
 [-0.33333333  0.25        0.08333333]]
w^hat is:  [-2.33333333  5.         -0.66666667]



---
**Task 6 (medium): Projection matrix♾️**
The projection matrix $P = A(A^\top A )^{-1}A^\top$ is, under certain conditions, equal to the identity matrix.
1. Give an example of a design matrix $A$ for which $P=I$.
2. Explain why projection matrices are usually not identity matrices.
3. (optional) Prove a condition for which $P=I$. Hint: when is $A^\top A=I$?.


---

In [7]:
import numpy as np

_X = np.array([
    [1.0, 0.0],
    [0.0, 1.0]

])
y = np.array([0.0, 1.0])
_X_tranposed = _X.T

print("X transposed is: \n",_X_tranposed)

# Here i try to find the product of x transposed and x
XT_T = _X_tranposed @ _X
print("X transposed and X is: \n",XT_T)

# the inverse of the above is:
inverse = np.linalg.inv(XT_T)
print("inverse of (X transposed and X) is: \n", inverse)

# (X^T X)^-1 X^T
inverse_with_X_Transposed = inverse @ _X_tranposed
print("(X^T X)^-1 X^T, i.e. P: \n", inverse_with_X_Transposed)

# At last, we now put the y value on:
w_hat = inverse_with_X_Transposed @ y
print("w^hat is: ", w_hat)

# f(x) = -0,66667x^2 + 5x -2,33333

X transposed is: 
 [[1. 0.]
 [0. 1.]]
X transposed and X is: 
 [[1. 0.]
 [0. 1.]]
inverse of (X transposed and X) is: 
 [[1. 0.]
 [0. 1.]]
(X^T X)^-1 X^T, i.e. P: 
 [[1. 0.]
 [0. 1.]]
w^hat is:  [0. 1.]


# 2
Projection matrices are usually not identity matrices because they reduce the dimensionality of vectors by removing components orthogonal to the target subspace. The identity matrix only occurs when the projection is onto the entire space.

